name: Dispatch Acta Approval Email

on:
  workflow_dispatch:
    inputs:
      acta_id:
        description: 'Project ID (acta_id)'
        required: true

jobs:
  send-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          inline: |
            aws lambda invoke               --function-name sendApprovalEmail               --payload '{"acta_id": "${{ github.event.inputs.acta_id }}"}'               response.json