name: Dispatch One-Off Acta Approval Email
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID'
        required: true
      recipient:
        description: 'E-mail to send Acta to'
        required: true

jobs:
  send-approval:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invoke Lambda
        run: |
          set -euo pipefail
          PAY='{"project_id":"${{ inputs.project_id }}","recipient":"${{ inputs.recipient }}"}'
          aws lambda invoke \
            --function-name sendApprovalEmail \
            --cli-binary-format raw-in-base64-out \
            --payload "$PAY" out.json
          cat out.json
          jq -e '.statusCode == 200' out.json
