name: Dispatch Acta Approval Email

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID (project_id)'

jobs:
  send-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          inline: |
            aws lambda invoke \
              --function-name sendApprovalEmail \
              --payload '{\"project_id\": \"${{ github.event.inputs.project_id }}\", \"recipient\": \"${{ github.event.inputs.recipient }}\", \"pdf_key\": \"${{ github.event.inputs.pdf_key }}\"}' \
              --cli-binary-format raw-in-base64-out \
              response.json
            cat response.json
