name: Deploy to Lambda via ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v3

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🐳 Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 703671891952.dkr.ecr.us-east-2.amazonaws.com/projectplace-lambda

      - name: 🛠 Build and push Docker image to ECR
        run: |
          docker build -t projectplaceextractor .
          docker tag projectplaceextractor:latest 703671891952.dkr.ecr.us-east-2.amazonaws.com/projectplace-lambda:latest
          docker push 703671891952.dkr.ecr.us-east-2.amazonaws.com/projectplace-lambda:latest

      - name: 🚀 Update AWS Lambda function with latest image
        run: |
          aws lambda update-function-code \
            --function-name ProjectPlaceDataExtractor \
            --image-uri 703671891952.dkr.ecr.us-east-2.amazonaws.com/projectplace-lambda:latest \
            --region us-east-2

      - name: ✅ Deployment complete
        run: echo "✅ Lambda deployment completed successfully!"
