name: Deploy sendApprovalEmail Lambda
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: 🚀 Deploy sendApprovalEmail
        env:
          AWS_ACCOUNT_ID:       ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION:           ${{ secrets.AWS_REGION }}
          DYNAMODB_TABLE_NAME:  ${{ secrets.DYNAMODB_TABLE_NAME }}
          EMAIL_SOURCE:         ${{ secrets.EMAIL_SOURCE }}
          S3_BUCKET_NAME:       ${{ secrets.S3_BUCKET_NAME }}
          ACTA_API_ID:          ${{ secrets.ACTA_API_ID }}
        run: python3 scripts/deploy_send_approval_email.py
