name: Deploy sendApprovalEmail

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Grab your code
      - uses: actions/checkout@v4

      # 2️⃣ Configure AWS creds
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region:            ${{ secrets.AWS_REGION }}
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 3️⃣ Run your Python deploy script (zips + updates code+config)
      - name: Deploy sendApprovalEmail Lambda
        run: |
          python3 scripts/deploy_send_approval_email.py
