name: Deploy → sendApprovalEmail

on:
  workflow_dispatch:  # ✅ This enables the 'Run workflow' button
  
  push:
    paths:
      - approval/send_approval_email.py
      - .github/workflows/deploy_approval.yml

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    env:
      REGION:           ${{ secrets.AWS_REGION || 'us-east-2' }}
      FUNCTION_NAME:    sendApprovalEmail
      ZIP_FILE:         send_approval_email.zip
      EMAIL_SOURCE:     ${{ secrets.EMAIL_SOURCE }}
      TEST_PID:         ${{ secrets.TEST_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.REGION }}

      - run: aws sts get-caller-identity

      - run: zip -j $ZIP_FILE approval/send_approval_email.py

      - name: Update code
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://$ZIP_FILE

      - name: Dry-run invoke (no email sent)
        run: |
          aws lambda invoke \
            --function-name $FUNCTION_NAME \
            --cli-binary-format raw-in-base64-out \
            --payload '{"project_id":"'"$TEST_PID"'", "dry_run": true, "email_source": "'"$EMAIL_SOURCE"'" }' \
            out.json
          cat out.json
