name: Deploy Auto-Approve Lambda
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FUNCTION_NAME: autoApprovePending
      AWS_REGION: us-east-2
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}
    - run: |
        zip auto.zip auto_approve_pending.py
        aws lambda update-function-code \
          --function-name "$FUNCTION_NAME" \
          --zip-file fileb://auto.zip
