name: Deploy Approval Workflow

on:
  push:
    paths:
      - 'scripts/deploy_send_approval_email.py'
      - 'approval/**'
      - 'config/**'

jobs:
  deploy-approval:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v3

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 📦 Install Python dependencies
        run: pip install boto3

      - name: 🚀 Run sendApprovalEmail deployment
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          DYNAMODB_TABLE_NAME: ${{ secrets.DYNAMODB_TABLE_NAME }}
          EMAIL_SOURCE: ${{ secrets.EMAIL_SOURCE }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: python3 scripts/deploy_send_approval_email.py
