name: ONE-SHOT ▸ Rebuild ProjectPlace table_v2

on:
  workflow_dispatch:        # manual Run-workflow button only

jobs:
  rebuild:
    runs-on: ubuntu-latest

    env:
      TABLE_NAME: ProjectPlace_DataExtrator_landing_table_v2
      REGION:      ${{ secrets.AWS_REGION || 'us-east-2' }}
      EXPORT_S3:   s3://pp-table-backups/${{ github.run_id }}/
      TEST_PID:    ${{ secrets.TEST_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.REGION }}

      # 1️⃣ optional export (succeeds or continues)
      - name: Export current table to S3 (best-effort)
        continue-on-error: true
        run: |
          if aws dynamodb describe-table --table-name "$TABLE_NAME" >/dev/null 2>&1; then
            ARN=$(aws dynamodb describe-table --table-name "$TABLE_NAME" \
                  --query 'Table.TableArn' --output text)
            aws dynamodb export-table-to-point-in-time \
              --table-arn "$ARN" \
              --s3-bucket "$EXPORT_S3" \
              --export-format DYNAMODB_JSON \
              --region "$REGION" || true
          fi

      # 2️⃣ delete table if present
      - name: Delete table (if present)
        run: |
          if aws dynamodb describe-table --table-name "$TABLE_NAME" >/dev/null 2>&1; then
            aws dynamodb delete-table --table-name "$TABLE_NAME"
            aws dynamodb wait table-not-exists --table-name "$TABLE_NAME"
            echo "Table deleted."
          else
            echo "Table already absent."
          fi

      # 3️⃣ recreate with correct key schema
      - name: Create table with project_id (S) + card_id (S)
        run: |
          aws dynamodb create-table \
            --table-name "$TABLE_NAME" \
            --attribute-definitions \
                AttributeName=project_id,AttributeType=S \
                AttributeName=card_id,AttributeType=S \
            --key-schema \
                AttributeName=project_id,KeyType=HASH \
                AttributeName=card_id,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST \
            --region "$REGION"
          aws dynamodb wait table-exists --table-name "$TABLE_NAME"
          echo "✅ Table recreated and ACTIVE."

      # 4️⃣ seed table immediately by invoking the by-ID Lambda
      - name: Seed table with by-ID Lambda
        run: |
          echo "{\"project_id\":\"${TEST_PID}\"}" > payload.json
          aws lambda invoke \
            --function-name projectMetadataEnricherById \
            --cli-binary-format raw-in-base64-out \
            --payload file://payload.json out.json
          cat out.json
          grep -q '"statusCode": 200' out.json

      - name: Reminder
        run: |
          echo "::notice ::Rebuild complete. Delete or rename this workflow file now to prevent accidental re-runs."
